[package]
name = "remote_input_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.26.2"
strum_macros = "0.26.2"
enigo = "*"
tokio = { version = "1", features = ["full"] }
tungstenite = "0.23.0"
tokio-tungstenite = "0.23.1"
futures-util = "0.3"
systray = "0.4"
fltk = "1.4.32"
qrcode = "0.14.1" 
image = "0.25.1"